global using Microsoft.Extensions.Logging;
global using EHRPlatform.Common.Events;
global using EHRPlatform.Common.Messaging;
global using EHRPlatform.Common.Security;
global using EHRPlatform.Services.Appointment.Data;
global using EHRPlatform.Services.Appointment.Data.Configuration;
global using EHRPlatform.Services.Appointment.Data.Seeds;
global using EHRPlatform.Services.Appointment.Domain.Events;
global using AppointmentReminder = EHRPlatform.Services.Appointment.Features.Appointments.Domain.AppointmentReminder;
global using ProviderAvailability = EHRPlatform.Services.Appointment.Features.Appointments.Domain.ProviderAvailability;
global using EHRPlatform.Services.Appointment.Domain.Enums;
global using EHRPlatform.Services.Appointment.Application.AppointmentManagement;
global using EHRPlatform.Services.Appointment.Application.AppointmentManagement.Mappers;
global using EHRPlatform.Services.Appointment.Application.AppointmentManagement.Responses;
global using EHRPlatform.Services.Appointment.Application.AppointmentManagement.Requests;
global using EHRPlatform.Services.Appointment.Features.Appointments.Commands;
global using EHRPlatform.Services.Appointment.Features.Appointments.Queries;
global using EHRPlatform.Services.Appointment.Features.Appointments.Validation;
// Type alias to resolve 'Appointment' vs namespace 'EHRPlatform.Services.Appointment' ambiguity
global using Appointment = EHRPlatform.Services.Appointment.Features.Appointments.Domain.Appointment;
