namespace EHRPlatform.Common.Infrastructure.Security;

/// <summary>
/// Encryption and hashing service for sensitive data.
/// Uses AES-256-GCM for authenticated encryption and PBKDF2 for hashing.
/// </summary>
public interface IEncryptionService
{
    /// <summary>
    /// Encrypt plaintext using AES-256-GCM.
    /// Returns Base64-encoded ciphertext with embedded nonce and auth tag.
    /// </summary>
    string Encrypt(string plaintext);

    /// <summary>
    /// Decrypt ciphertext encrypted with Encrypt().
    /// </summary>
    string Decrypt(string ciphertext);

    /// <summary>
    /// Generate a one-way hash using PBKDF2-SHA256.
    /// Returns Base64-encoded hash with embedded salt.
    /// </summary>
    string Hash(string value);

    /// <summary>
    /// Verify a plaintext value against a hash generated by Hash().
    /// Uses constant-time comparison to prevent timing attacks.
    /// </summary>
    bool VerifyHash(string value, string hash);
}

