<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Description>Document Management & File Storage Service - API Layer</Description>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\FileStorage.Application\FileStorage.Application.csproj" />
    <ProjectReference Include="..\FileStorage.Persistence\FileStorage.Persistence.csproj" />
    <ProjectReference Include="..\FileStorage.Infrastructure\FileStorage.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\..\EHR-System\building-blocks\EventBus\src\EventBus.csproj" />
    <ProjectReference Include="..\..\..\..\EHR-System\building-blocks\Observability\src\Observability.csproj" />
    <ProjectReference Include="..\..\..\..\EHR-System\building-blocks\Common\src\Common.csproj" />
  </ItemGroup>
</Project>
