<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Description>API Gateway - Infrastructure (routing, discovery, rate limiting, middleware)</Description>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Yarp.ReverseProxy" Version="2.2.0" />
    <PackageReference Include="AspNetCoreRateLimit" Version="5.1.0" />
    <PackageReference Include="Consul" Version="1.7.14.6" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ApiGateway.Domain\ApiGateway.Domain.csproj" />
  </ItemGroup>
</Project>
