<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Serilog" Version="3.0.1" />
    <PackageReference Include="Serilog.Sinks.Console" Version="5.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Billing.Domain\Billing.Domain.csproj" />
    <ProjectReference Include="..\Billing.Persistence\Billing.Persistence.csproj" />
  </ItemGroup>

  <!-- Building Blocks -->
  <ItemGroup>
    <ProjectReference Include="..\..\..\..\building-blocks\SharedKernel\src\SharedKernel.csproj" />
    <ProjectReference Include="..\..\..\..\building-blocks\Common\src\Common.csproj" />
    <ProjectReference Include="..\..\..\..\building-blocks\Security\src\Security.csproj" />
    <ProjectReference Include="..\..\..\..\building-blocks\EventBus\src\EventBus.csproj" />
  </ItemGroup>

</Project>
