<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>EHRPlatform.Services.Clinical.Domain</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EHRPlatform.BuildingBlocks.SharedKernel" Version="1.0.0" />
  </ItemGroup>

</Project>
