// <auto-generated />
using System;
using EHRPlatform.BuildingBlocks.Common.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EHRPlatform.Services.OutboxProcessor.Data.Migrations
{
    [DbContext(typeof(MultiServiceOutboxDbContext))]
    partial class MultiServiceOutboxDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EHRPlatform.Common.Events.OutboxEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AggregateId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("EventData")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsPublished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("MaxPublishAttempts")
                        .HasColumnType("integer");

                    b.Property<int>("PublishAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RoutingKey")
                        .HasColumnType("text");

                    b.Property<string>("Transport")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AggregateId")
                        .HasDatabaseName("IX_OutboxEvent_AggregateId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_OutboxEvent_CreatedAt");

                    b.HasIndex("EventType")
                        .HasDatabaseName("IX_OutboxEvent_EventType");

                    b.HasIndex("IsPublished", "PublishAttempts", "CreatedAt")
                        .HasDatabaseName("IX_OutboxEvent_Unpublished");

                    b.ToTable("OutboxEvents");
                });
#pragma warning restore 612, 618
        }
    }
}

