apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ehr-platform

resources:
  - namespace.yaml
  - rbac.yaml
  - configmap.yaml
  - secrets.yaml
  - network-policy.yaml
  - api-gateway.yaml
  - identity-service.yaml
  - patient-service.yaml
  - services-remaining.yaml
  - ingress.yaml
  - hpa.yaml
