apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ehr-platform

commonLabels:
  app.kubernetes.io/part-of: ehr-platform
  app.kubernetes.io/managed-by: kustomize
  environment: base

commonAnnotations:
  managed-by: "kubectl"
  documentation: "https://github.com/Mostafa-SAID7/EHR-Systems-Microservices"

resources:
  - 00-namespace.yaml
  - 01-configmaps.yaml
  - 02-secrets.yaml
  - 03-storage.yaml
  - 04-policies.yaml

replacements: []

patchesStrategicMerge: []
